/**
 * Project-level command (script) definitions and their run records.
 *
 * Definitions live in `.yorz/config.json` (git-tracked, so a worktree checked
 * out on the same branch inherits them). Run records and logs live under
 * `.yorz/tmp/commands/`, which is gitignored.
 */

export interface CommandDef {
  /** Short id generated by the service. */
  id: string
  name: string
  cli: string
  createdAt: number
}

export type CommandRunStatus = 'running' | 'exited' | 'killed' | 'failed'

export interface CommandRun {
  runId: string
  commandId: string
  /**
   * Snapshot taken at spawn time so the record stays readable after the
   * definition is deleted.
   */
  name: string
  cli: string
  pid: number
  status: CommandRunStatus
  startedAt: number
  endedAt?: number
  exitCode?: number | null
  signal?: string | null
  /** POSIX path relative to the project root, safe to paste into an agent prompt. */
  logFile: string
}

export interface CommandOutputChunk {
  /** Byte offset in the log file this chunk starts at. */
  offset: number
  chunk: string
}

export interface CommandOutputSlice {
  /** Byte offset the returned text starts at. */
  offset: number
  text: string
  /** Total log file size in bytes. */
  size: number
  /** True when the head of the log was dropped to cap the response size. */
  truncated: boolean
}

/** Tail cap for an offset-less output read: 256 KiB. */
export const OUTPUT_TAIL_LIMIT = 256 * 1024

/** Run records finished longer ago than this are reaped on startup: 7 days. */
export const RUN_RETENTION_MS = 7 * 24 * 60 * 60 * 1000

export function commandsDir(projectPath: string): string {
  return `${projectPath}/.yorz/tmp/commands`
}

/** Relative POSIX log path for a run, as stored in `CommandRun.logFile`. */
export function runLogRelPath(runId: string): string {
  return `.yorz/tmp/commands/${runId}.log`
}
